Title:Brought all windows examples up to date
All Windows examples are up to date with what they need to run in an
embedded environment or pc environment.

The embedded_gcc_example need to be fixed to include the necessary
files to compile.

Current errors:
    - undefined reference to `_exit'
    - undefined reference to `_sbrk'
    - undefined reference to `_write'
    - undefined reference to `_close'
    - undefined reference to `_fstat'
    - undefined reference to `_isatty'
    - undefined reference to `_lseek'
    - undefined reference to `_read'
    - undefined reference to `_kill'
    - undefined reference to `_getpid'